version: '3.8'
services:
  devops-db:
    image: postgres:13
    container_name: devops-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rahat-website-be
    networks:
      - devops

  # devosps-redis:
  #   container_name: devosps-redis
  #   image: redis:6.2.12 
  #   restart: always
  #   command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - devops

  rahat-website-be:
    image: rahat-website-be:devOps
    container_name: rahat-website-be
    volumes:
      - .env:/usr/src/app/.env`
    ports:
      - 3333:3333
    networks:
      - devops

networks:
  devops: